title: "/dev/null"
locale: "pt-BR"
description: "Algumas coisas acabam aqui..."
url: "http://blog.augustopascutti.com"
search: false
comments: false
remote_theme: "mmistakes/so-simple-theme"
read_time: true

exclude:
  - bin
  - Gemfile
  - Gemfile.lock
  - Makefile
  - docker-compose.yml
  - README.md
  - usr
  - _drafts

timezone: America/Sao_Paulo
date_format: "%Y-%m-%d"
source: .
destination: ./_site
plugins:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap
whitelist:
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-sitemap

future: false
lsi: false
permalink: date
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6

author:
  name: "Augusto Pascutti"
  email: "augusto.hp@gmail.com"
  picture: "http://s.gravatar.com/avatar/89de242e444d231e9928320af0417571?s=200"
  twitter: "@augustohp"
  links:
    - title: LastFM
      url: https://www.last.fm/user/augusto_hp
      icon: fab fa-lastfm
    - title: Mastodon
      url: https://phpc.social/@augustohp
      icon: fab fa-mastodon
    - title: GitHub
      url: https://github.com/augustohp
      icon: fab fa-github
    - title: LinkedIn
      url: https://www.linkedin.com/in/augustohp
      icon: fab fa-linkedin
    - title: StackExchange
      url: http://stackoverflow.com/users/447920/augusto-pascutti
      icon: fab fa-stack-exchange
footer_links:
  - title: LastFM
    url: https://www.last.fm/user/augusto_hp
    icon: fab fa-lastfm
  - title: Mastodon
    url: https://phpc.social/@augustohp
    icon: fab fa-mastodon
  - title: GitHub
    url: https://github.com/augustohp
    icon: fab fa-github
  - title: LinkedIn
    url: https://www.linkedin.com/in/augustohp
    icon: fab fa-linkedin
  - title: StackExchange
    url: http://stackoverflow.com/users/447920/augusto-pascutti
    icon: fab fa-stack-exchange
feed:
  path: atom.xml
twitter:
  username: augustohp
google_fonts:
  - name: "Source Sans Pro"
    weights: "400,400i,700,700i"
  - name: "Lora"
    weights: "400,400i,700,700i"
# vim: et ts=4 sw=4:
