name: Link Health

on:
  repository_dispatch:
  schedule:
    - cron: "00 10 * * 1"
  workflow_dispatch:
    inputs:
      create_issue:
        description: "If 'true' creates an issue with the broken links report."
        required: true
        default: true
        type: string

env:
  OPTION_CREATE_ISSUE: ${{ inputs.create_issue || 'true' }}

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Broken Links? 🤔
        id: lychee
        uses: lycheeverse/lychee-action@v2
        with:
          args: --config ./.lychee.toml --no-progress .
          failIfEmpty: false
          debug: false
          format: markdown
          output: report-broken-links.md

      - name: Report broken links
        if: ${{ failure() && env.OPTION_CREATE_ISSUE == 'true' }}
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: 🤖 Broken Links Report
          content-filepath: report-broken-links.md
          labels: Bug